### PR TITLE
emit error when a problem occured regarding zlib deflate/inflate

### PR DESCRIPTION
**Pull request by franck34**

### CODE REVIEW

**Comment by kevincennis** [comment]
Thanks so much for this. I can't believe we didn't have proper error handling around the `translate` calls.

For the sake of making this a bit more generic, would you be willing to submit a pull request to [fringe](https://github.com/StarryInternet/fringe) instead? That's the library that `missive` is based on. You could just wrap the calls to `this.translate` in the `Encoder` and `Parser` classes.

If not, no worries. I'll try to get that done tonight and release new versions of both libraries so you've got something that'll deal with these errors.

Thanks again.

**Comment by franck34** [comment]
Hi !

Let me try to PR on fringe ;)

**Comment by franck34** [comment]
done, as a try 

https://github.com/StarryInternet/fringe/pull/4

**Comment by kevincennis** [comment]
Closed in favor of StarryInternet/fringe#4

**Pull request closed without merging**
